import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Herobanner from '../components/elements/Herobanner'

import { productionBrowserSourceMaps } from '../next.config'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Herobanner />
    
    </div>
  )
}






  
  
  